"""create rating item table

Revision ID: 14db5afa223a
Revises: 
Create Date: 2026-08-12 15:52:00.752337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14db5afa223a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('status IN (0, 1, 2)', name='ck_rating_item_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_item_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_rating_item_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_item_status'))
        batch_op.drop_index(batch_op.f('ix_rating_item_name'))

    op.drop_table('rating_item')
    # ### end Alembic commands ###
