"""ensure one active item per topic

Revision ID: 17d449f16bc0
Revises: 835f792246d7
Create Date: 2026-08-18 14:27:58.238756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d449f16bc0'
down_revision: Union[str, Sequence[str], None] = '835f792246d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.create_index('uq_rating_item_topic_active', ['topic_id'], unique=True, sqlite_where=sa.text('status = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_index('uq_rating_item_topic_active', sqlite_where=sa.text('status = 1'))

    # ### end Alembic commands ###
