"""change participant from topic to rating item

Revision ID: 20b147ebe256
Revises: faeb23c303bc
Create Date: 2026-08-18 16:02:50.493260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b147ebe256'
down_revision: Union[str, Sequence[str], None] = 'faeb23c303bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_item_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating_item_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer_type', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rating_item_id'], ['rating_item.id'], name='fk_rating_item_participant_rating_item_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating_item_id', 'client_id', name='uq_rating_item_participant_item_client')
    )
    with op.batch_alter_table('rating_item_participant', schema=None) as batch_op:
        batch_op.create_index('ix_rating_item_participant_item_reviewer', ['rating_item_id', 'reviewer_type'], unique=False)

    with op.batch_alter_table('rating_topic_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_topic_participant_topic_id'))
        batch_op.drop_index(batch_op.f('ix_rating_topic_participant_topic_reviewer'))

    op.drop_table('rating_topic_participant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_topic_participant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('reviewer_type', sa.SMALLINT(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['rating_topic.id'], name=op.f('fk_rating_topic_participant_topic_id')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'client_id', name=op.f('uq_rating_topic_participant_topic_client'))
    )
    with op.batch_alter_table('rating_topic_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_topic_participant_topic_reviewer'), ['topic_id', 'reviewer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_topic_participant_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('rating_item_participant', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_item_participant_item_reviewer')

    op.drop_table('rating_item_participant')
    # ### end Alembic commands ###
