"""add expert token and reviewer type

Revision ID: 38804408f81e
Revises: 6660feac93f2
Create Date: 2026-08-17 09:06:53.854452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38804408f81e'
down_revision: Union[str, Sequence[str], None] = '6660feac93f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_token', sa.String(length=64), nullable=True))

    with op.batch_alter_table('rating_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewer_type', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_result', schema=None) as batch_op:
        batch_op.drop_column('reviewer_type')

    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_column('expert_token')

    # ### end Alembic commands ###
