"""add rating topic participant

Revision ID: 3c9248d29b35
Revises: 19ea5023f8c1
Create Date: 2026-08-18 15:23:42.657512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9248d29b35'
down_revision: Union[str, Sequence[str], None] = '19ea5023f8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_topic_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('reviewer_type', sa.SmallInteger(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['rating_topic.id'], name='fk_rating_topic_participant_topic_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'client_id', name='uq_rating_topic_participant_topic_client')
    )
    with op.batch_alter_table('rating_topic_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_topic_participant_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_rating_topic_participant_topic_reviewer', ['topic_id', 'reviewer_type'], unique=False)

    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_item_name'))
        batch_op.create_index(batch_op.f('ix_rating_item_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_item_name'))
        batch_op.create_index(batch_op.f('ix_rating_item_name'), ['name'], unique=False)

    with op.batch_alter_table('rating_topic_participant', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_topic_participant_topic_reviewer')
        batch_op.drop_index(batch_op.f('ix_rating_topic_participant_topic_id'))

    op.drop_table('rating_topic_participant')
    # ### end Alembic commands ###
