"""add rating item expert_weight

Revision ID: 6660feac93f2
Revises: e5222effcbec
Create Date: 2026-08-16 00:17:19.491822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6660feac93f2'
down_revision: Union[str, Sequence[str], None] = 'e5222effcbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_column('expert_weight')

    # ### end Alembic commands ###
