"""create rating topic

Revision ID: e1bb1f77812b
Revises: 38804408f81e
Create Date: 2026-08-18 14:19:20.132223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bb1f77812b'
down_revision: Union[str, Sequence[str], None] = '38804408f81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('distinguish_expert', sa.Boolean(), nullable=False),
    sa.Column('expert_weight', sa.Float(), nullable=True),
    sa.Column('public_limit', sa.Integer(), nullable=False),
    sa.Column('expert_limit', sa.Integer(), nullable=True),
    sa.Column('expert_token', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('expert_limit IS NULL OR expert_limit > 0', name='ck_rating_topic_expert_limit'),
    sa.CheckConstraint('expert_weight IS NULL OR (expert_weight > 0 AND expert_weight < 1)', name='ck_rating_topic_expert_weight'),
    sa.CheckConstraint('public_limit > 0', name='ck_rating_topic_public_limit'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_topic_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_topic_name'))

    op.drop_table('rating_topic')
    # ### end Alembic commands ###
