"""add distinguish expert to rating item

Revision ID: e5222effcbec
Revises: 552b38b755d1
Create Date: 2026-08-15 23:30:38.268199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e5222effcbec'
down_revision: Union[str, Sequence[str], None] = '552b38b755d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'distinguish_expert',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_column('distinguish_expert')

    # ### end Alembic commands ###
