"""remove expert config from rating item

Revision ID: faeb23c303bc
Revises: 3c9248d29b35
Create Date: 2026-08-18 15:48:28.032185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faeb23c303bc'
down_revision: Union[str, Sequence[str], None] = '3c9248d29b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.drop_column('expert_weight')
        batch_op.drop_column('distinguish_expert')
        batch_op.drop_column('expert_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_token', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('distinguish_expert', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('expert_weight', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
